### ISSUE TITLE
What is port2

### ISSUE THREAD

**Issue by diegodlh** [softins/jamulus-web#5]
@softins, thanks for this great tool! This is not an issue, but rather a question. I wasn't sure where to post it. Sorry if I wasn't meant to post it here.
In commit f388511dd6bb2e9a64466ae1b72488cbc8875474 you added support for port2. But what is port2 exactly? Can you explain, or point to any Jamulus documentation / discussion message?
Thanks!

**Comment by softins** [comment]
Hi Diego, no problem! The explanation is quite involved, so I hope it makes sense!

The port2 value comes from the back-end, which you can see at https://github.com/softins/jamulus-php. The back-end acts like a Jamulus client for fetching data from the servers, and then presents it to the front-end in JSON.

When a server registers with a central server, the central server makes a note of the server's IP address and the source port from which the request comes. The central server will reply to the registering server by using that port number as a destination port in the reply.

When a client, such as my back-end, requests a server list from the central server, this server list contains the IP address and port number that were stored at registration. When the client wants to connect to a specific server, it uses the IP and port that it has been told by the central server.

Now, many servers are behind a NAT router or other kind of firewall, which might not be expecting an unsolicited connection attempt from a client. In order to overcome that, the central server does some magic. When a client requests a server list, the central server also tells each server in that list to send a ping message direct to the requesting client. It doesn't actually matter whether the client receives it. The objective is to open a session on the server's firewall so that it will be ready to receive any request to it from the client.

Now, under normal circumstances, the ping message from the server to the client should come from the same source port as the port number which that server registered at the central server. However, when developing the back-end, I discovered that the messages from some servers would actually come from a *different* source port. When that happens, the back-end notes that new port number as port2, and uses that port when requesting the version, OS and client list from the server. The front end then displays this port2 number in parentheses ().

While investigating this with one server operator who had noticed the dual port numbers on his server, we discovered that it was due to a setting on his firewall/router. There was a security feature called something like "randomise source port number", which would map the original source port from the sender into a different port number. When he turned that feature off, we found that he no longer generated a different port2 value.

For servers that display a different port2 in Jamulus Explorer, some Jamulus clients may find they have trouble connecting or even seeing those servers, due to the port mapping being different than expected.

Hope this all makes sense and is useful!

**Comment by diegodlh** [comment]
This is AMAZING. Thank you very much @softins. I definitely wasn't expecting such a detailed and enlightening response. Couldn't be clearer. Thank you!!

**Comment by diegodlh** [comment]
BTW, if you maybe happen to know why I may be experiencing [this](https://sourceforge.net/p/llcon/discussion/server/thread/f72b293af0/), I'd be glad to hear your thoughts about it there :)

**Comment by ErnestoAcc** [comment]
Hi @softins  
Could you help me to get rid of port2? Should I serch the randomiser in the firewall (windows 10) or the roiter (Dlink 610N)?
Best,
Ernesto

**Comment by softins** [comment]
> Could you help me to get rid of port2?

Hi Ernesto, I think it is much more likely to be a configuration in the router (D-Link 610N). I am not familiar with that router and was unable to find much detail online (it appears to be a Latin America model).

An application such as Jamulus sets its own port number, which the OS should not change.

**Comment by ErnestoAcc** [comment]
Thanks!
Here is how I've configured the port forwarding (English version
autotranslated)
[image: image.png]

And, this tab seems to be useful, isn't it?
[image: image.png]

It is the same page as the one for a DIR-635. model in this video:
https://www.youtube.com/watch?v=HP5b8QRYyOk

I did used all combinations with these two tabs and this third one too:

[image: image.png]

... I cannot get rid of that port2




Am Fr., 11. Sept. 2020 um 12:06 Uhr schrieb Tony Mountifield <
notifications@github.com>:

**Comment by softins** [comment]
Your images did not come through. I think you can only include images if you post your reply via the github web site, not by replying in an email.

I found a manual for the DIR-635 at http://files.dlink.com.au/Products/DIR-635/Manuals/DIR-635_B3_Manual_v2.00.pdf

Look at page 45. Do you have SPI enabled? If so, try turning it off to see if it makes a difference. You could also try the Endpoint Independent setting for UDP, and if anti-spoof checking is enabled, try turning it off.

Finally, see the Device Information display shown on page 63. What are the first two numbers in your WAN IP address?

Is your server "Lalo"?

**Comment by ErnestoAcc** [comment]
Thanks!
No, nothing of that worked. SPI and anti-spoof were already disabled and
the Endpoint Independent setting for UDP didn't make any change.
wan ip: 192.168
BerSJ is our server now.

Am Fr., 11. Sept. 2020 um 13:53 Uhr schrieb Tony Mountifield <
notifications@github.com>:

**Comment by softins** [comment]
Ok, if your WAN IP address is 192.168.x.x, that indicates that your ISP has given you a private IP for your connection, not a public one. If you visit http://myipaddress.com, you will see that your public IP is different from your WAN IP. That means that your ISP is applying NAT to your connection within their infrastructure, and the source port randomisation is most likely being applied by the ISP, not by your router.

I think your only solution is to contact your ISP and ask them to give you a public, non-NAT IP address for your connection, because you want to run a server.

**Comment by Rob-NY** [comment]
I am running a MacOS server behind a consumer grade router and also saw the PORT2 on explorer.  There were no firewall settings in place to support this.  

If I started the server through via the command line (not by clicking the .app), with -s, I also saw the PORT2.  However, if I started it through the command line headless (-s -n), then I did NOT see PORT2.  

I had used the same machine as a CLIENT before using it as a server.  Ultimately, when I erased all the client config files and restarted the server, the PORT2 went away.    Now I do not see PORT2 either starting from the command line or using the .app. 

I know this issue is old, but hoping that might help someone.

**Comment by Rob-NY** [comment]
> I am running a MacOS server behind a consumer grade router and also saw the PORT2 on explorer. There were no firewall settings in place to support this.
> 
> If I started the server through via the command line (not by clicking the .app), with -s, I also saw the PORT2. However, if I started it through the command line headless (-s -n), then I did NOT see PORT2.
> 
> I had used the same machine as a CLIENT before using it as a server. Ultimately, when I erased all the client config files and restarted the server, the PORT2 went away. Now I do not see PORT2 either starting from the command line or using the .app.
> 
> I know this issue is old, but hoping that might help someone.

**Comment by Rob-NY** [comment]
With respect to the above - after upgrading to 3.7, I always see Port2 when starting the server through the UI.  The only way I've been able to remove the Port2 listing is to start "regular" jamulus via the command line with -s -n.
